// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: api/specs/specs.proto

package specs

import (
	_ "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineSpec is stored in Omni in the infra provisioner state.
type MachineSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Schematic     string                 `protobuf:"bytes,2,opt,name=schematic,proto3" json:"schematic,omitempty"`
	TalosVersion  string                 `protobuf:"bytes,3,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	VmId          int32                  `protobuf:"varint,4,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Node          string                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	ImageName     string                 `protobuf:"bytes,6,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_api_specs_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_specs_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_api_specs_specs_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MachineSpec) GetSchematic() string {
	if x != nil {
		return x.Schematic
	}
	return ""
}

func (x *MachineSpec) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *MachineSpec) GetVmId() int32 {
	if x != nil {
		return x.VmId
	}
	return 0
}

func (x *MachineSpec) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *MachineSpec) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

var File_api_specs_specs_proto protoreflect.FileDescriptor

const file_api_specs_specs_proto_rawDesc = "" +
	"\n" +
	"\x15api/specs/specs.proto\x12\fproxmoxspecs\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xac\x01\n" +
	"\vMachineSpec\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\tschematic\x18\x02 \x01(\tR\tschematic\x12#\n" +
	"\rtalos_version\x18\x03 \x01(\tR\ftalosVersion\x12\x13\n" +
	"\x05vm_id\x18\x04 \x01(\x05R\x04vmId\x12\x12\n" +
	"\x04node\x18\x05 \x01(\tR\x04node\x12\x1d\n" +
	"\n" +
	"image_name\x18\x06 \x01(\tR\timageNameB>Z<github.com/alinanova21/omni-infra-provider-proxmox/api/specsb\x06proto3"

var (
	file_api_specs_specs_proto_rawDescOnce sync.Once
	file_api_specs_specs_proto_rawDescData []byte
)

func file_api_specs_specs_proto_rawDescGZIP() []byte {
	file_api_specs_specs_proto_rawDescOnce.Do(func() {
		file_api_specs_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_specs_specs_proto_rawDesc), len(file_api_specs_specs_proto_rawDesc)))
	})
	return file_api_specs_specs_proto_rawDescData
}

var file_api_specs_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_specs_specs_proto_goTypes = []any{
	(*MachineSpec)(nil), // 0: proxmoxspecs.MachineSpec
}
var file_api_specs_specs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_specs_specs_proto_init() }
func file_api_specs_specs_proto_init() {
	if File_api_specs_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_specs_specs_proto_rawDesc), len(file_api_specs_specs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_specs_specs_proto_goTypes,
		DependencyIndexes: file_api_specs_specs_proto_depIdxs,
		MessageInfos:      file_api_specs_specs_proto_msgTypes,
	}.Build()
	File_api_specs_specs_proto = out.File
	file_api_specs_specs_proto_goTypes = nil
	file_api_specs_specs_proto_depIdxs = nil
}
